### ISSUE TITLE
Error: invalid config/module.ini file

### ISSUE THREAD

**Issue by lguariento** [Daniel-KM/Omeka-plugin-CsvImportPlus#15]
Hello,

on Omeka S 2.1.0 I get 'Error: invalid config/module.ini file' after copying the folder inside the `modules` folder and renaiming it as `CsvImportPlus`, and going to the /module page via browser.

Best,
Luca

**Comment by Daniel-KM** [comment]
Hi, 
For Omeka S, the plugin is merged in the upstream [CSV Import](https://https://github.com/omeka-s-modules/CSVImport), even if my version has some more fixes and improvements. 
In all cases, the folder where the module is unzipped must be the name of the module, without "-master", and case sensitively. 
Furthermore, it's recommended to use the release version instead of the master, because the release contains dependencies.

**Comment by Daniel-KM** [comment]
So, this repository is for the Omeka Classic version.
